<?xml version="1.0" encoding="utf-8"?><Database Name="WKX" Class="WKXDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\WKX.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WKXConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIP" Member="VIP">
    <Type Name="VIP">
      <Column Name="Id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VIP_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VIP_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDCard" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StarTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>